### ISSUE TITLE
Backport to 1.19.2

### ISSUE THREAD

**Issue by ItsaGlitch1** [onebeastchris/GeyserHacks-Fabric#1]
I'm building a server in 1.19.2 to be able to work with some world gen plugins and have GeyserMC setup on it. Was hoping if there could be a release for 1.19.2 in the near future

**Comment by onebeastchris** [comment]
hey.
Considering Geyser-fabric only supports the latest available version, and 1.19.3 support being dropped when 1.19.4 releases - a 1.19.2 version isn't likely to be made by me. I'll take a look, if it's just a version change then I might do it, but I'm not making a separate 1.19.2 release for the reasons stated above. 
Feel free to backport it yourself if it's urgent though.

**Comment by onebeastchris** [comment]
https://modrinth.com/mod/geyserhacks-fabric/version/y4jgnvh3 try dis one

**Comment by ItsaGlitch1** [comment]
Tested the features, no issues. Thanks!
