### ISSUE TITLE
Update to 1.19.4

### ISSUE THREAD

**Issue by CleMooling** [onebeastchris/GeyserHacks-Fabric#2]
As title, because of the update of the game, the old version does no longer work.

**Comment by onebeastchris** [comment]
https://modrinth.com/mod/geyserhacks-fabric/version/0.76.0+1.19.4
I've updated the mod to 1.19.4.

**Comment by CleMooling** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
