### ISSUE TITLE
Support for Fabric server behind Velocity proxy?

### ISSUE THREAD

**Issue by itslilscorp** [onebeastchris/GeyserHacks-Fabric#27]
Any chance this mod could be used when the server is behind a Velocity proxy?

**Comment by onebeastchris** [comment]
That's already possible if you use:
- floodgate-fabric on the fabric backend server 
- fabric proxy lite for velocity modern forwarding support 
- set up floodgate-velocity to send Floodgate data to the backend server.

For more info, see the Floodgate setup guide for velocity/fabric:
https://wiki.geysermc.org/floodgate/setup/
