### ISSUE TITLE
Player cannot paddle boats in water

### ISSUE THREAD

**Issue by axieum** [onebeastchris/GeyserHacks-Fabric#4]
Boats cannot be controlled while in water.

Version: 1.0.1+1.20
Geyser MC: 2.1.1-SNAPSHOT

**Comment by onebeastchris** [comment]
Unable to reproduce. Please send a full log

**Comment by onebeastchris** [comment]
https://github.com/onebeastchris/Hurricane-Fabric/commit/7c6296e99fcb2461c1e7d9c3f6ff56b183279e5b
fixed in this commit; will backport & upload to modrinth in a minute. Thanks for reporting!
