### ISSUE TITLE
[1.21] Fix basename of JAR file

### ISSUE THREAD

**Issue by HatTrkPatrk** [onebeastchris/GeyserHacks-Fabric#40]
![image](https://github.com/onebeastchris/Hurricane-Modded/assets/5185596/e9449bf5-7857-4fd5-965e-f74680997f1d)
![image](https://github.com/onebeastchris/Hurricane-Modded/assets/5185596/7250ce59-5d9a-418e-9868-7bc3709f04c3)

Add the keyword "hurricane" back to the basename of the JAR file.

**Comment by onebeastchris** [comment]
Thanks, should be resolved now.
